apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: mqtls-tr-bah-
spec:
  taskRef:
    name: mqtls-source-to-image-buildah
  serviceAccountName: pipeline
  inputs:
   resources:
    - name: source
      resourceRef:
        name: git-source
   params:
    - name: pathToContext
      value: ./     
    - name: imageUrl
      value: image-registry.openshift-image-registry.svc:5000/da-build-project/ibm-mqadvanced-server-tls-build
    - name: imageTag
      value: "latest"