apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: mqtls-pr-bahdep-
spec:
  pipelineRef:
    name: mqtls-build-and-deploy-pipeline-buildah
  resources:
    - name: source
      resourceRef:
        name: git-source        
  params:
    - name: qmgrName
      value: mytektqmgr
    - name: pathToYamlFile
      value: "mqdeploymentconfig/ibmmq.yaml"
    - name: pathToContext
      value: ./     
    - name: imageUrl
      value: image-registry.openshift-image-registry.svc:5000/da-build-project/ibm-mqadvanced-server-tls-build
    - name: imageTag
      value: "latest"