apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: mqtls-tr-dep-
spec:
  taskRef:
    name: mqtls-deploy-using-kubectl
  serviceAccountName: pipeline
  inputs:
   resources:
    - name: source
      resourceRef:
        name: git-source
   params:
    - name: qmgrName
      value: mytektqmgr
    - name: pathToYamlFile
      value: "mqdeploymentconfig/ibmmq.yaml"     
    - name: imageUrl
      value: image-registry.openshift-image-registry.svc:5000/da-build-project/ibm-mqadvanced-server-tls-build
    - name: imageTag
      value: "latest"