kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: mqtls-jen-bc
  namespace: da-build-project
  labels:
    build: mqtls-jen-bc
  annotations:
    description: Defines how to build the messaging application
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'ibm-mqadvanced-server-tls-build:latest'
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: da-build-project
        name: 'ibm-mqadvanced-server-integration:9.1.3.0-r4-amd64'
  source:
    type: Git
    dockerfile: |-
      FROM ibm-mqadvanced-server-integration:9.1.3.0-r4-amd64
      USER mqm
      COPY TLSPRQM1.mqsc /etc/mqm/
      COPY NOTLS.mqsc /etc/mqm/
      COPY MYDEFS.mqsc /etc/mqm

      COPY TLSPRQM1.kdb /etc/mqm/
      COPY TLSPRQM1.crt /etc/mqm/
      COPY TLSPRQM1.rdb /etc/mqm/
      COPY TLSPRQM1.sth /etc/mqm/    
    git:
      uri: 'https://github.com/DAVEXACOM/ibm-mqadvanced-server-tls-build.git'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  postCommit: {}
  triggers: []