apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: mqtls-jen
  name: mqtls-jen-pipeline
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
        agent {
        node {
        label 'nodejs' 
          }
         }
        options { 
         timeout(time: 20, unit: 'MINUTES') 
        }
        stages {
        stage('build') {
        steps {
            script {
                openshift.withCluster() {
                    openshift.withProject() {
                        echo "Using project: ${openshift.project()}"
                        openshift.selector("bc", "mqtls-jen-bc").startBuild("--wait")
                    }
                }
            }
         }
        }
        stage('deploy') {
         when {
          expression {
          openshift.withCluster() {
            return !openshift.selector('dc', 'mqtls-jen').exists()
          }
          }
          }
         steps {
          script {
            openshift.withCluster() {
                openshift.withProject() {
                def created = openshift.newApp( " ibm-mqadvanced-server-tls-build:latest", "--name=mqtls-jen", "--env=LICENSE=accept", "--env=MQ_QMGR_NAME=myjenqmgr")
                echo "new-app created ${created.count()} objects named: ${created.names()}"
                created.narrow('svc').expose("--name=mqtls-listener","--port=1414")
                
                 
                }
            }
        }
        }
        }
        }
        }
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
  triggers: []